version: 2

sources:
  - name: dst_db_source
    description: 'Table relationelle'
    database: DST_DB
    schema: PUBLIC
    tables:
      - name: ARTIST
        description: 'Nom des artists'

      - name: ALBUM
        description: 'Nom des albums'

      - name: GENRE
        description: 'Genre de musique'
      
      - name: MEDIATYPE
        description: 'Type de media'
      
      - name: PLAYLIST
        description: 'listes des musique'
      
      - name: PLAYLISTTRACK
        description: 'track et playslist'
      
      - name: TRACK
        description: 'Les titres de musique'


models:
  - name: dim_artist_v1
    description: "model de l'artist"
    columns:
      - name: artist_id
        description: "clé primaire"
        tests:
          - unique
          - not_null

      - name: name
        description: "nom du chanteur"
      
      - name: birthyear
        description: "date de naissance"
      
      - name: country
        description: "pays"

  - name: dim_album_v1
    description: "model de l'albums"
    columns:
      - name: album_id
        description: "clé primaire"
        tests:
          - unique
          - not_null

      - name: title
        description: "titre de l'album"
      
      - name: artist_id
        description: "id de l'artist"
      
      - name: prod_year
        description: "l'annee de production"

      - name: cd_year
        description: "l'annee du cd"
  
  - name: dim_genre_v1
    description: "model du genre"
    columns:
      - name: genre_id
        description: "clé primaire"
        tests:
          - unique
          - not_null

      - name: name
        description: "nom du genre"

  - name: dim_mediatype_v1
    description: "model du type de media"
    columns:
      - name: mediatype_id
        description: "clé primaire"
        tests:
          - unique
          - not_null

      - name: name
        description: "nom du media type"
  
  - name: dim_track_v1
    description: "model d'un track"
    columns:
      - name: track_id
        description: "clé primaire"
        tests:
          - unique
          - not_null

      - name: name
        description: "nom de la chanson"
      
      - name: composer
        description: "nom du compositeur"

  
  - name: fact_track_cd_v1
    description: "model principal"
    columns:
      - name: track_id
        description: "clé primaire"
        tests:
          - not_null
          - unique

      - name: album_id
        description: "id de l'album"
      
      - name: artist_id
        description: "id de l'artist"
      
      - name: genre_id
        description: "id de du genre"
      
      - name: mediatype_id
        description: "id du type de media"
      
      - name: milliseconds
        description: "la durée du morceau"
      
      - name: bytes
        description: "bytes"
      
      - name: unitprice
        description: "prix"
      
      - name: track_count
        description: "nombre de chansons"
      
  


